version: '3.1'
services:    
    versioncontrol:
        build:
          context: .
          dockerfile: src/Dockerfile          
        image: versioncontrol-service      
        ports: 
            - "8080:8080"   
        env_file: .env             
        container_name: versioncontrol-service